### ISSUE TITLE
Problem with loading datasets as NoneType

### ISSUE THREAD

**Issue by richard-peng-xia** [guyrosin/tempobert#1]
Hi, I am trying to use train_tempobert.py for training in the task of sentence time prediction, using the following script:
`
python train_tempobert.py 
    --model_name_or_path bert-base-uncased 
    --train_path /DIR/tempobert/datasets/nyt_with10k_every10 
    --do_train 
    --output_dir /DIR/output
    --time_embedding_type prepend_token
    --time_mlm_probability 0.9
    --max_seq_length 128
`
However, codes have been loading the data set section error, as shown in the figure below, showing reading as NoneType. I don't know how to solve it, so I come to ask you how to solve it. And if possible, I hope you can send me the training script at that time, thanks~
![image](https://user-images.githubusercontent.com/68063744/147487348-e0150d22-85c8-4853-8091-b07a0fe8e36a.png)

**Comment by guyrosin** [comment]
Hi Richard,

Thank you for reporting this! I've just pushed a fix (problem was I somehow forgot to specify the temporal dataset loading script as one of `train_tempobert.py`'s arguments).
Please let me know if you have any additional questions.

**Comment by richard-peng-xia** [comment]
Sorry to bother you again. When I used the train_tempobert.py you uploaded yesterday for training, there was no problem in dataset loading and preprocessing. But when I run temporal_data_collator.py, there is an error. It says that special_tokens_mask is none, the error picture is as follows. I print the batch, and find that there are only three keys composed of attention_mask,input_ids, and token_type_ids in this dictionary. So there is no special_tokens_mask. I would like to ask why this leads to such a error. Thanks.
![image](https://user-images.githubusercontent.com/68063744/147634881-6470d38e-edcb-4be9-892d-6b7eb68fd3d4.png)

**Comment by Richard88888** [comment]
The last problem has been solved. If you have the same problem, you can refer to my practice. Add `if` special_tokens_mask else None`  to line 62 of temporal_data_collator.py and the effect is as follows. It was eventually resolved.
![image](https://user-images.githubusercontent.com/68063744/147657531-8a32c2d1-7540-4961-8c3d-250f94cb9b9f.png)

**Comment by richard-peng-xia** [comment]
The last problem has been solved. If someone has the same problem, he can refer to my practice. Add `if special_tokens_mask else None`  to line 62 of temporal_data_collator.py and the effect is as follows. It was eventually resolved.
![image](https://user-images.githubusercontent.com/68063744/147657659-c367d4e4-9043-4c1b-9304-6f24e185b55a.png)

**Comment by guyrosin** [comment]
Thank you! 
I've just pushed another fix which allows using special_tokens_mask, as it improves performance. Hope it helps!
